version: '3.1'
services:
    web:
        image: cloudowski/docker-pets:1.0
        deploy:
            mode: replicated
            replicas: 3
        healthcheck:
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - 8080:5000
            - 8081:7000
        environment:
            DB: 'db'
            THREADED: 'True'
            OPTION_A: 'SmallLions'
        networks:
            - backend
        volumes:
            - ./web:/app

    db:
        image: consul:0.7.2
        command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1
        deploy:
            replicas: 3
        ports:
            - 8500:8500 
        environment:
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        networks: 
            - backend
      
networks:
    backend:


