global:
  ingress:
    configureCertmanager: false
    class: "nginx"
    annotations:
      "kubernetes.io/tls-acme": true
      "cert-manager.io/cluster-issuer": letsencrypt-staging
      "nginx.ingress.kubernetes.io/proxy-body-size": 512m
      "nginx.ingress.kubernetes.io/proxy-buffering": "on"
      "nginx.ingress.kubernetes.io/proxy-connect-timeout": "15"
      "nginx.ingress.kubernetes.io/proxy-read-timeout": "30"
      "nginx.ingress.kubernetes.io/proxy-send-timeout": "30"
