# Minimal settings
global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: "nginx"
    annotations:
      "kubernetes.io/tls-acme": true
      "cert-manager.io/cluster-issuer": letsencrypt-prod
      "nginx.ingress.kubernetes.io/proxy-body-size": 512m
      "nginx.ingress.kubernetes.io/proxy-buffering": "on"
      "nginx.ingress.kubernetes.io/proxy-connect-timeout": "15"
      "nginx.ingress.kubernetes.io/proxy-read-timeout": "30"
      "nginx.ingress.kubernetes.io/proxy-send-timeout": "30"
      "nginx.ingress.kubernetes.io/proxy-max-temp-file-size": "512m"
  hosts:
    domain: test.example.com
  minio:
    enabled: true
  registry:
    enabled: false
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
deployments:
  hpa:
    minReplicas: 1
    maxReplicas: 2
gitlab:
  sidekiq:
    minReplicas: 1
    maxReplicas: 2
    resources:
      requests:
        cpu: 100m
  gitlab-shell:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  webservice:
    ingress:
      tls:
        secretName: gitlab-gitlab-tls
    workerProcesses: 1
    resources:
      requests:
        cpu: 100m
minio:
  ingress:
    tls:
      secretName: gitlab-minio-tls
registry:
  enabled: false
  ingress:
    tls:
      secretName: gitlab-registry-tls

postgresql:
  primary:
    resources:
      requests:
        cpu: 100m
  master:
    resources:
      requests:
        cpu: 100m
