apiVersion: v1
kind: Service
metadata:
  labels:
    app: pets
    tier: backend
  name: pets-node
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 8080
    targetPort: admin
    name: admin
  selector:
    app: pets
    tier: backend
  type: NodePort
