expose:
  tls:
    secretName: harbor-staging-letsencrypt

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
