apiVersion: v1
kind: Pod
metadata:
  name: pets
  labels:
      app: pets
      tier: backend

spec:
  containers:
  - image: cloudowski/docker-pets:1.0
    name: pets
    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 5

    ports:
    - containerPort: 5000
      name: http
    - containerPort: 7000
      name: admin

    envFrom:
    - configMapRef:
        name: pets-config

    volumeMounts:
          # name must match the volume name below
          - name: admin-secret
            mountPath: /run/secrets/pets

  volumes:
    - name: admin-secret
      secret:
        secretName: pets-admin-password

  terminationGracePeriodSeconds: 5
