apiVersion: v1
kind: Pod
metadata:
  name: consul
  labels:
      app: pets
      tier: db

spec:
  containers:
  - image: consul:0.7.2
    name: consul
    livenessProbe:
      exec:
        command:
        - consul
        - members
      initialDelaySeconds: 300
      timeoutSeconds: 5
    ports:
    - containerPort: 8500
      name: http
    - containerPort: 8400
      name: rpc
    - containerPort: 8300
      name: server
