ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "10m"
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging

  tls:
      - secretName: gitea-letsencypt-stage
        hosts:
          - git.app.labs.k8sworkshops.com

persistence:
  enabled: true
  giteaSize: 1Gi
  accessMode: ReadWriteOnce

mariadb:
  enabled: true
  replication:
    enabled: false

  master:
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 2Gi

